### ISSUE TITLE
Correlation.py and event_detail.py script

### ISSUE THREAD

**Issue by nivi1501** [gz/autoperf#3]
I have successfully generated data in the out file, but I encounter following error while using event_detail script:
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'AVG.OFFCORE_RESPONSE.ALL_RFO.L3_MISS.REMOTE_HIT_FORWARD'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/nivedita/Documents/Sem4/GITHUB/autoperf-master/analyze/profile/event_detail.py", line 68, in <module>
    make_plot(args.dir, args.features)
  File "/home/nivedita/Documents/Sem4/GITHUB/autoperf-master/analyze/profile/event_detail.py", line 56, in make_plot
    plot_events(df, features, filename, from_directory)
  File "/home/nivedita/Documents/Sem4/GITHUB/autoperf-master/analyze/profile/event_detail.py", line 37, in plot_events
    ax1.plot(df[feature], label=feature)
  File "/home/nivedita/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nivedita/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'AVG.OFFCORE_RESPONSE.ALL_RFO.L3_MISS.REMOTE_HIT_FORWARD'

Moreover, I encountered assertion error while running correlation.py script.

Is there something that I am missing out. Please let me know.
Kindly, answer these queries as well:
1. Can I analyze multiple codes using autoperf in separate command window. Will it affect my results?
2. Will there be any affect of background process on the tool? What will be the effect, what can I do to avoid that?

**Comment by gz** [comment]
Hi,

it looks like the event AVG.OFFCORE_RESPONSE.ALL_RFO.L3_MISS.REMOTE_HIT_FORWARD is not found in the CSV file. Can you past it maybe on gist.github.com?
